name: Labelize
jobs:
  labelize:
    name: Labelize
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '\ci')
    env:
      GH_REPO: ${{ github.repository }}
      GH_TOKEN: ${{ secrets.F3D_CI_LABEL }}
    steps:
    - name: GARALT debug probe
      run: 'printf ''GARALT_DBG: comment.body = %s\n'' "$(printf ''%s\n'' ''${{ toJSON(github.event.comment.body) }}'')"'
      continue-on-error: true
    - name: Analyze comment
      shell: bash
      run: |
        label="${{github.event.comment.body}}"
        label=${label#* }
        label=${label%% *}
        echo "F3D_LABEL_COMMENT=$label" >> $GITHUB_ENV
env:
  GARALT_SECRET: ${{ secrets.GARALT }}
on: issue_comment
